parameters:
#    h_ncms_project.example.class: HNcms\ProjectBundle\Example

services:
#    h_ncms_project.example:
#        class: %h_ncms_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
