parameters:
#    h_ncms_finance.example.class: HNcms\FinanceBundle\Example

services:
#    h_ncms_finance.example:
#        class: %h_ncms_finance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
