parameters:
#    h_ncms_message.example.class: HNcms\MessageBundle\Example

services:
#    h_ncms_message.example:
#        class: %h_ncms_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
