parameters:
#    hn_user.example.class: HNcms\UserBundle\Example

services:
#    hn_user.example:
#        class: %hn_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
